### ISSUE TITLE
Move to curly quotes

### ISSUE THREAD

**Issue by IntermittentlyRupert** [IntermittentlyRupert/hpnofp-ebook#10]
Use `‘ ’ “ ”` (curly quotes) for quotes and apostrophes instead of `' "` (straight quotes) like we do now.

**Comment by ThrawnCA** [comment]
That could be a very big job, or else an error-prone one if done using an automatic search and replace.

**Comment by IntermittentlyRupert** [comment]
Agreed, and I'd also want to do #11 first, or adding future chapters will be a pain.

My thinking is that the bulk of the work can probably be scripted a bit more intelligently than a naive search-and-replace, but I need to do some experimentation to see how consistent the usage is.

The way I'd do it, at least for a first pass, would be:

- Double quotes:
  - Track whether or not we're inside double-quote marks
  - When we hit a double-quote, examine the surrounding characters to heuristically determine whether it looks like an open- or close-quote mark.
  - If there's a mismatch, refer it for manual review
- Single quotes:
  - Assume they're always apostrophes (since we use double-quotes for speech)
  - Again, verify this by examining the surrounding characters and applying heuristics, prompt for manual review if it looks weird.

This should be fairly easy to bash out a prototype and see how many cases need manual review.

**Comment by ThrawnCA** [comment]
Single quotes are definitely used in pairs sometimes, to highlight 'questionable' words.

**Comment by ThrawnCA** [comment]
Rather than building an intelligent replacement, I'd probably just start assembling patterns to pick the low hanging fruit, then see what's left and make new patterns based on that.

For example, comma-space-quote and dot-space-quote should become opening quotes, while the versions without spaces should become closing quotes. Also, a quote at the start of a line should be an opening quote. After replacing those, you might find that you still have, say, hyphen-quote, which is likely a closing quote, and quote-hyphen, which will be opening. Etc.

**Comment by ThrawnCA** [comment]
Turns out? Calibre has a built-in feature to do this. I'll see how it goes.

**Comment by ThrawnCA** [comment]
Branch is ready, just need to merge https://github.com/IntermittentlyRupert/hpnofp-ebook/pull/13 first.
