### ISSUE TITLE
Script the e-book creation

### ISSUE THREAD

**Issue by ThrawnCA** [IntermittentlyRupert/hpnofp-ebook#3]
I'll provide a shell script to generate EPUB format; it's basically just a zip. Conversion to other formats would depend on the presence of libraries like Calibre.

**Comment by IntermittentlyRupert** [comment]
Thanks, I'd appreciate it!

I've been using ePubPack to generate the archive, since there are some particular requirements in the spec around how the archive should be structured.

Would you please make sure your output validates with [EPUBCheck](https://github.com/w3c/epubcheck) (from memory there's a few pre-existing warnings around the `h3` tags in the `ol` element in `TOC.xhtml`, so don't worry about those).

**Comment by IntermittentlyRupert** [comment]
Just got a chance to take a look, and it looks like the script in PR #4 actually does corrupt the image files.

It seems to be because the step to collapse white-space doesn't seem to exclude the image files, which are stored in `OEBPS`.

Should be fairly easy to resolve this by filtering by file extension.

**Comment by ThrawnCA** [comment]
Oops. New pull request should fix it.

**Comment by IntermittentlyRupert** [comment]
Yep, verified it on my end as well, thanks.
